CREATE TABLE `fund`.`fund_config` (
  `ID`   bigint(20) NOT NULL AUTO_INCREMENT ,
  `FUND_CODE`  varchar(10) NOT NULL COMMENT '基金代码',
  `FUND_TYPE`  int(11) NOT NULL COMMENT '基金类型',
  `FUND_NAME`  varchar(100) NOT NULL COMMENT '基金名称' ,
  `CREATED_AT`   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATED_AT`   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `RECORD_VERSION`  int(11) NOT NULL DEFAULT '1',
  `IS_DELETED`   tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='基金配置';
